"""add serial and reading

Revision ID: 301b684da042
Revises: e527636baf99
Create Date: 2026-01-25 05:55:44.575572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301b684da042'
down_revision = 'e527636baf99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reading', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_column('reading')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
